registry:
  kind: etcd
  endpoints:
    - localhost:2379
  username:
  password:
service:
  namespace: cn.lemonit.cloud
  secret_id: none
  secret_key: none
  override_host: localhost
  port: 32100

gateway:
  server:
    http_port: 32000